# Generated by Django 3.2.4 on 2021-07-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_students_on_course'),
        ('accounts', '0003_alter_user_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_courses',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='courses.Course'),
        ),
    ]
