# Generated by Django 3.2.4 on 2022-01-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsApp', '0003_alter_test_students'),
        ('accounts', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_tests',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='testsApp.Test'),
        ),
    ]
