# Generated by Django 3.2.7 on 2022-05-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_trainingdirections'),
        ('accounts', '0014_rename_mentors_qroups_mentor_mentors_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_training_directions',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='courses.TrainingDirections', verbose_name='Направления подготовки'),
        ),
    ]
