# Generated by Django 3.2.7 on 2022-05-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsApp', '0005_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='chosen_answers',
            field=models.ManyToManyField(related_name='tests_results', to='testsApp.Answer', verbose_name='Ответы учащегося'),
        ),
    ]
