# Generated by Django 3.2.7 on 2022-05-11 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsApp', '0007_testresult_is_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_to_question', to='testsApp.question', verbose_name='Вариант ответа к вопросу'),
        ),
    ]
