version: "3"

services:
  backend:
    build:
      context: ./new_math_site
    command: gunicorn new_math_site.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./new_math_site/frontend
    volumes:
      - react_build:/frontend
  nginx:
    image: nginx:latest
    ports:
      - 80:8000
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
