# Generated by Django 3.2.7 on 2022-05-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0002_auto_20220503_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Группы обучающихся', 'verbose_name_plural': 'Группы обучающихся'},
        ),
    ]
