# Generated by Django 3.2.7 on 2022-05-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0003_alter_studentgroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBookNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_book_number', models.CharField(max_length=30)),
            ],
        ),
    ]
