# Generated by Django 3.2.7 on 2022-05-16 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0005_alter_studentbooknumber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbooknumber',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_book_numbers', to='student_groups.studentgroup'),
            preserve_default=False,
        ),
    ]
