# Generated by Django 3.2.7 on 2022-06-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0007_studentgroup_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='group_mentors',
            field=models.ManyToManyField(blank=True, related_name='student_groups', to='accounts.Mentor', verbose_name='Преподаватели группы'),
        ),
    ]
