# Generated by Django 3.2.7 on 2022-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, unique=True)),
                ('group_mentors', models.ManyToManyField(blank=True, related_name='student_groups', to='accounts.Mentor')),
            ],
        ),
    ]
