# Generated by Django 3.2.7 on 2022-05-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0004_studentbooknumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentbooknumber',
            options={'verbose_name': 'Номер зачетной книжки', 'verbose_name_plural': 'Номера зачетных книжек'},
        ),
    ]
