# Generated by Django 3.2.7 on 2022-05-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_slug_lesson_lesson_slug'),
        ('accounts', '0007_mentor'),
        ('student_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_groups.studentgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_courses',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentors_qroups',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='student_groups.StudentGroup'),
        ),
    ]
