# Generated by Django 3.2.7 on 2022-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220503_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='student',
            name='student_book_number',
            field=models.CharField(default='18-kb-pr-1', max_length=30),
            preserve_default=False,
        ),
    ]
