# Generated by Django 3.2.7 on 2022-05-09 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0004_studentbooknumber'),
        ('courses', '0007_rename_slug_lesson_lesson_slug'),
        ('testsApp', '0003_alter_test_students'),
        ('accounts', '0012_auto_20220509_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_book_number',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student_groups.studentbooknumber'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_tests',
            field=models.ManyToManyField(blank=True, related_name='student_tests', to='testsApp.Test'),
        ),
    ]
