# Generated by Django 3.2.7 on 2022-05-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220509_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='mentors_qroups',
            new_name='mentors_groups',
        ),
    ]
