# Generated by Django 3.2.7 on 2022-06-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0007_studentgroup_start_year'),
        ('accounts', '0015_mentor_mentor_training_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student_groups.studentgroup'),
        ),
    ]
