# Generated by Django 3.2.7 on 2022-05-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_slug_lesson_lesson_slug'),
        ('student_groups', '0002_auto_20220503_1211'),
        ('testsApp', '0003_alter_test_students'),
        ('accounts', '0009_auto_20220503_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_tests',
        ),
        migrations.AddField(
            model_name='mentor',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('user_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('student_courses', models.ManyToManyField(blank=True, related_name='accounts', to='courses.Course')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_groups.studentgroup')),
                ('student_tests', models.ManyToManyField(blank=True, related_name='accounts', to='testsApp.Test')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
    ]
