# Generated by Django 3.2.7 on 2022-05-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220508_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='login',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_name',
        ),
    ]
