# Generated by Django 3.2.4 on 2021-06-13 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('num_of_modules', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Курсы',
            },
        ),
    ]
