# Generated by Django 3.2.4 on 2021-07-04 10:07

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание курса')),
                ('num_of_modules', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество модулей')),
                ('students_on_course', models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200, verbose_name='Название')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Контент модуля')),
                ('slug', models.SlugField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Модули курсов',
            },
        ),
    ]
