# Generated by Django 3.2.4 on 2021-06-13 15:34

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_of_modules',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество модулей'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название курса'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=200, verbose_name='Название')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Контент модуля')),
                ('slug', models.SlugField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Модули курсов',
            },
        ),
    ]
