# Generated by Django 3.2.4 on 2021-07-14 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_alter_course_students_on_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students_on_course',
            field=models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
