# Generated by Django 3.2.4 on 2021-08-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210808_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='slug',
            new_name='lesson_slug',
        ),
    ]
