# Generated by Django 3.2.7 on 2022-05-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_slug_lesson_lesson_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_code', models.CharField(max_length=8)),
                ('direction_name', models.CharField(max_length=100)),
            ],
        ),
    ]
