# Generated by Django 3.2.7 on 2022-06-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220529_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='theme',
        ),
    ]
