# Generated by Django 3.2.4 on 2021-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_students_on_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num_of_modules',
        ),
        migrations.AddField(
            model_name='module',
            name='theme',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
