# Generated by Django 3.2.7 on 2022-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_trainingdirections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingdirections',
            options={'verbose_name': 'Направление подготовки', 'verbose_name_plural': 'Направления подготовки'},
        ),
        migrations.AlterField(
            model_name='trainingdirections',
            name='direction_code',
            field=models.CharField(max_length=8, verbose_name='Код направления'),
        ),
        migrations.AlterField(
            model_name='trainingdirections',
            name='direction_name',
            field=models.CharField(max_length=100, verbose_name='Название направления подготовки'),
        ),
    ]
