# Generated by Django 3.2.4 on 2021-08-07 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тесты', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='test',
            name='students',
            field=models.ManyToManyField(related_name='succeded_students', to=settings.AUTH_USER_MODEL, verbose_name='Студенты, прошедшие тест'),
        ),
    ]
