# Generated by Django 3.2.7 on 2022-05-11 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_mentors_qroups_mentor_mentors_groups'),
        ('testsApp', '0004_alter_test_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_questions', models.ManyToManyField(related_name='tests_results', to='testsApp.Question', verbose_name='Вопросы теста')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_results', to='accounts.student')),
            ],
        ),
    ]
