# Generated by Django 3.2.7 on 2022-05-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsApp', '0009_testresult_test_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_mark',
            field=models.IntegerField(default=2, verbose_name='Оценка за тест'),
        ),
    ]
