# Generated by Django 3.2.7 on 2022-05-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsApp', '0010_auto_20220515_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_time',
            field=models.IntegerField(default=0),
        ),
    ]
